---

package_assets: on
compress_assets: off

javascripts:
  ie:
  - public/javascripts/ie-css3.js
  - public/javascripts/html5.js
  base:
  - public/javascripts/jquery.js
  - public/javascripts/jquery.ui.js
  - public/javascripts/jquery.rails.js
  - public/javascripts/jquery.metadata.js
  - public/javascripts/jquery.easyAccordion.js
  - public/javascripts/jquery.innerfade.js
  - public/javascripts/jquery.zweatherfeed.js
  - public/javascripts/application.js
