development:
  adapter: mysql2
  database: boarrd
  username: root
  password: "maglione"
  host: localhost

production:
  adapter: mysql
  database: boarrd
  username: boarrd
  password: w3l41k4
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
